# Generated by Django 4.0.3 on 2022-03-15 05:11

from django.db import migrations
from sorl.thumbnail.fields import ImageField


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
